### PR TITLE
Lots of improvements, added FedEx and USPS tracking, etc.

### PR DESCRIPTION
**Pull request by alertedsnake**
There's a lot in here, I know. Basic changes:

Added working FedEx and working USPS tracking (for XXnnnnnnnnnXX type USPS numbers).

Disabled USPS validation while I work it out. Added FedEx validation.

Improved all three so that the result object has the full tracking history available as well as just the last status.

Improved the xml_to_dict() function so it can deal with turning multiple entries of the same type into lists.

Added a bunch of error checking that showed up in some special cases I was testing.

Made the TrackingInfo object inherit from dict so it can be used as a dict or an object (useful for me for converting to JSON on a web app).

Let me know what you think :)

### CODE REVIEW

**Comment by mw44118** [comment]
Why didn't this get merged in?

**Comment by netllama** [comment]
Srsly, why can't this stuff get merged?  This module is virtually useless without the merge.

**Comment by storborg** [comment]
The work looks great, but needs some adaptation (which I don't have time to do on this module) to be acceptable to merge. Currently:
- It makes breaking API changes.
- It is self-described as incomplete ("disabled USPS validation").
- It is not PEP8 compliant.
- It adds filesystem access on every instantiation of `Package`.
- It uses module-level state.
- Tests would be nice, as well, particularly for the added validation tools.

If you'd like to pick up the work and finish it, that would be very welcome. Alternatively, feel free to fork it.

**Comment by alertedsnake** [comment]
Since this PR went 3 years without any comments at all, and 4 without one from the maintainer, I'm treating this as yet another abandonware library, and I certainly won't be bothering to finish this work.  If someone wants to take over from here, feel free.

**Comment by alichaudry** [comment]
I don't mind taking a look at this in my free time (and at the very least, doing some quick, high-level pep8).

The problem is, I'm unable to fork off from @alertedsnake's fork of `packagetrack`. I need @alertedsnake's `master` branch to continue the work he was doing.

**Comment by alertedsnake** [comment]
Why exactly can't you fork that?  I can do it just fine from another account.

**Comment by alichaudry** [comment]
I am able to fork from your branch, but it become a fork of @storborg's `master` instead of your `master`. I need to be able to continue off of your code.

**Comment by alertedsnake** [comment]
Ah, I don't know how that works with Github.  I know how it works if I could commit to storborg's master, but beyond that, I suppose you could just clone my branch into one of your own.

Doing a quick web search suggests that forking a fork is entirely possible.  You could certainly fork the real master and rebase it off my fork.

**Comment by alichaudry** [comment]
Okay @alertedsnake, I was able to setup your `master` branch as a remote tracking branch so I should be good to go.

**Comment by alertedsnake** [comment]
Okay I'm going to just rework this whole thing on my own, and release a derivative package, since there doesn't seem to be any interest here.

**Pull request closed without merging**
